# Generated by Django 6.0.1 on 2026-01-06 23:22

import acervo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_previsao_devolucao',
            field=models.DateField(default=acervo.models.data_padrao_devolucao),
        ),
    ]
