# Generated by Django 6.0.1 on 2026-01-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_alter_emprestimo_data_previsao_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
